# For more configuration details:
# https://docs.codecov.io/docs/codecov-yaml

# Check if this file is valid by running in bash:
# curl -X POST --data-binary @.codecov.yml https://codecov.io/validate

# Coverage configuration
# ----------------------
codecov:
  token: "7cb5afe5-5d97-4cad-b540-9d164b33bf00"

coverage:
  range: 60..80     # First number represents red, and second represents green
                    # (default is 70..100)
  round: up       # up, down, or nearest
  precision: 2      # Number of decimal places, between 0 and 5

# Ignoring Paths
# --------------
# which folders/files to ignore
ignore:
  - "*/tests/**.*"
  - "**/ui/**"
  - "**/__init__.py"
  - "setup.py"
  - "main.py"
