language: python
python:
  - "3.8.2"

# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - python -m pytest test --cov=./
  # - codecov --token=7cb5afe5-5d97-4cad-b540-9d164b33bf00
  - codecov
